//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoRedSocial
    {
        public int IdContactoRedSocial { get; set; }
        public int IdContacto { get; set; }
        public int IdRedSocial { get; set; }
        public string UrlPerfil { get; set; }
    
        public virtual Contacto Contacto { get; set; }
        public virtual RedSocial RedSocial { get; set; }
    }
}
